/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 * @version 0.7.0
 * @author Jabes
 */
public class ventana extends javax.swing.JFrame {
    private Timer tiempo;
    private int centesimaSegundo = 0, segundo = 0, minuto = 0, hora = 0;
    
    /**
     * Este Actionlistener hace un conteo de los segundos, al llegar a 60s aumenta a 1 min 
     * y reinicia los segundos, lo mismo para minutos, al llegar a 60 aumenta a 1 hora y reinicia minutos
    */
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimaSegundo++;
            if(centesimaSegundo == 100){
                centesimaSegundo = 0;
                segundo++;
            }
            if(segundo == 60){
                minuto++;
                segundo = 0;
            }
            if(minuto == 60){
                hora++;
                minuto = 0;
            }
            
            actualizarTiempo();
        }
    };
    
    /**
     * La funcion actualizarTiempo( ) usa un string que concatena las variables
     * hora, minuto, segundo, centesimas de segundo y si dichas variables solo contienen un digito
     * agrega a su izq un numero 0 para mantener siempre el mismo ancho de la etiqueta
    */
    private void actualizarTiempo(){
        String texto = (hora<=9?"0":""+hora+(minuto<=9?"0":"")+minuto+(segundo<=9?"0":"")+segundo+(centesimaSegundo<=9?"0":"")+centesimaSegundo);
        etiquetaTiempo.setText(texto);
    }
    
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        tiempo = new Timer(10,acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaCronometro = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        detener = new javax.swing.JButton();
        pausar = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaCronometro.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        etiquetaCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCronometro.setText("Cronometro");
        panel.add(etiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 30));

        etiquetaTiempo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00:00:00:00");
        panel.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 110));

        detener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        detener.setText("Detener");
        panel.add(detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 90, 40));

        pausar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pausar.setText("Pausar");
        pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarActionPerformed(evt);
            }
        });
        panel.add(pausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 40));

        iniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        panel.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 163, 90, 40));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        etiquetaFondo.setText("Cronometro");
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 227));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        iniciar.addActionListener(acciones);
        
    }//GEN-LAST:event_iniciarActionPerformed

    private void pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarActionPerformed
        pausar.addActionListener(acciones);
        
    }//GEN-LAST:event_pausarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detener;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JButton iniciar;
    private javax.swing.JPanel panel;
    private javax.swing.JButton pausar;
    // End of variables declaration//GEN-END:variables
}
